name: 'dockerhub'

on:
  pull_requst:
    branches:
      - main
    path:
      - terraform/**

jobs:
  DOS:
    name: running terraform plan
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: terraform

  steps:
    - name: 'Checkout'
      uses: actions/checkout@main

    - name: 'docker login'
      docker login -u  ferdinant122 -p ${{ secrets.DOCKERHUB_TOKEN }}


    - name: "Build"
      docker build -t ferdinant122/hello-world:1.0.1 .

    - name: "Push"
      docker push ferdinant122/hello-world:1.0.1
