name: 'dockerhub'

on:
  push:
    branches:
      - main
jobs:
  DOS:
    name: running terraform plan
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: terraform

    steps:
     - name: 'Checkout'
       uses: actions/checkout@main

     - name: 'docker login'
       run: docker login -u  ferdinant122 -p ${{ secrets.DOCKERHUB_TOKEN }}


     - name: "Build"
       run: docker build -t ferdinant122/hello-world:1.0.1 -t ferdinant122/hello-world:1.1.1 .

     - name: "Push"
       run: docker push ferdinant122/hello-world:1.0.1, ferdinant122/hello-world:1.1.1
