name: 'dockerhub'

on:
  push:
    branches:
      - main
jobs:
  DOS:
    name: running docker plan
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: docker

    steps:
     - name: 'Checkout'
       uses: actions/checkout@main

     - name: "Login github repo"
       run: docker login ghcr.io -u ferdinant122 --password "${{ secrets.GHREPO_TOKEN }}"


     - name: "Build"
       run: docker build -t ghcr.io/ferdinant122/github-actions:latest  .

     - name: "Push"
       run: docker push ghcr.io/ferdinant122/github-actions:latest
