name: 'dockerhub'

on:
  push:
    branches:
      - main
jobs:
  DOS:
    name: running docker plan
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: docker

    steps:
     - name: 'Checkout'
       uses: actions/checkout@main


     - name: "Build"
       run: docker build -t ferdinant122/hello-world:latest  .

     - name: "Push"
       run: docker push ghcr.io/ferdinant122/hello-world:latest
